CREATE TABLE tb_group
(
    id_group BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    acronym  VARCHAR(255),
    id_user  BIGINT,
    CONSTRAINT pk_tb_group PRIMARY KEY (id_group)
);

CREATE TABLE tb_permission
(
    id_permission BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description   VARCHAR(20) NOT NULL,
    CONSTRAINT pk_tb_permission PRIMARY KEY (id_permission)
);

CREATE TABLE tb_student
(
    id_student BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    id_group   BIGINT,
    CONSTRAINT pk_tb_student PRIMARY KEY (id_student)
);

CREATE TABLE tb_user
(
    id_user                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                VARCHAR(255),
    email                   VARCHAR(255),
    full_name               VARCHAR(255),
    password                VARCHAR(255),
    account_non_expired     BOOLEAN,
    account_non_locked      BOOLEAN,
    credentials_non_expired BOOLEAN,
    enabled                 BOOLEAN,
    CONSTRAINT pk_tb_user PRIMARY KEY (id_user)
);

CREATE TABLE tb_user_permission
(
    id_permission BIGINT NOT NULL,
    id_user       BIGINT NOT NULL
);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_email UNIQUE (email);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_username UNIQUE (username);

ALTER TABLE tb_group
    ADD CONSTRAINT FK_TB_GROUP_ON_ID_USER FOREIGN KEY (id_user) REFERENCES tb_user (id_user);

ALTER TABLE tb_student
    ADD CONSTRAINT FK_TB_STUDENT_ON_ID_GROUP FOREIGN KEY (id_group) REFERENCES tb_group (id_group);

ALTER TABLE tb_user_permission
    ADD CONSTRAINT fk_tbuseper_on_permission FOREIGN KEY (id_permission) REFERENCES tb_permission (id_permission);

ALTER TABLE tb_user_permission
    ADD CONSTRAINT fk_tbuseper_on_user FOREIGN KEY (id_user) REFERENCES tb_user (id_user);