/*create table if not exists public.tb_phase_one_answer
(
    id             bigint generated by default as identity
        primary key,
    answer         varchar(255),
    correct_answer varchar(255),
    is_correct     boolean,
    seconds        bigint,
    id_student     bigint
        constraint fkfj6c4fw6vjio6392xwpfhsw7
            references public.tb_student
);

create table if not exists public.tb_question
(
    id     bigint generated by default as identity
        primary key,
    answer varchar(255)
);


create table if not exists public.tb_statement
(
    id                    bigint generated by default as identity
        primary key,
    id_question           bigint
        constraint fkqcs3ibg8umhep2j4w56py1uon
            references public.tb_question,
    statement_description varchar(255)
);

CREATE TABLE tb_student_question
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_student     BIGINT,
    id_question    BIGINT,
    is_correct     BOOLEAN,
    answer         VARCHAR(255),
    correct_answer VARCHAR(255),
    seconds        BIGINT,
    CONSTRAINT pk_tb_student_question PRIMARY KEY (id)
);

ALTER TABLE tb_student_question
    ADD CONSTRAINT FK_TB_STUDENT_QUESTION_ON_ID_QUESTION FOREIGN KEY (id_question) REFERENCES tb_question (id);

ALTER TABLE tb_student_question
    ADD CONSTRAINT FK_TB_STUDENT_QUESTION_ON_ID_STUDENT FOREIGN KEY (id_student) REFERENCES tb_student (id_student);


*/