/*insert into public.tb_statement (id, id_question, statement_description)
values  (4, 3, 'você não consegue me ver'),
        (5, 3, 'fico dentro da terra'),
        (6, 3, 'uso para beber água'),
        (7, 4, 'segura árvores no chão'),
        (8, 4, 'absorvo nutrientes através dela'),
        (9, 4, 'as minhocas fazem companhia para esta parte'),
        (10, 2, 'por onde passa minha seiva'),
        (11, 2, 'possui uma casca dura'),
        (12, 2, 'alguns falam que segura meus braços'),
        (13, 5, 'posso ter diversas cores'),
        (14, 5, 'uma parte de mim se chama pétala'),
        (15, 5, 'tenho um cheiro agrádavel'),
        (16, 6, 'abelhas adoram me visitar'),
        (17, 6, 'dentro de mim existe um pozinho chamado pólen'),
        (18, 6, 'margaridas são exemplos desta parte'),
        (19, 7, 'minha cor é verde'),
        (20, 7, 'uso para respirar'),
        (21, 7, 'serve de alimento para muito herbívoros'),
        (22, 8, 'absorvo a luz do sol'),
        (23, 8, 'meu nariz, chamado estômato, fica nesta parte'),
        (24, 8, 'balançam e caem quando o vento sopra'),
        (25, 9, 'é doce e saboroso'),
        (26, 9, 'você pode comer'),
        (27, 9, 'protege minha semente'),
        (28, 10, 'laranja e banana são exemplos desta parte'),
        (29, 10, 'quando fica maduro'),
        (30, 10, 'pássarinhos gostam de comer'),
        (31, 11, 'de onde surgem novas plantas'),
        (32, 11, 'fico dentro dos frutos'),
        (33, 11, 'germinação é o que acontece quando esta parte encosta na terra'),
        (34, 12, 'posso dizer que são meus filhos'),
        (35, 12, 'cabe na palma da sua mão'),
        (36, 12, 'esta parte é formada depois que a flor seca.');*/